config/routes.rb
Rails.application.routes.draw do

#Definir named routes
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'loading' => 'escenarios#new'
  get 'contact', to: 'messages#new', as: 'contacto'
  post 'contact', to: 'messages#create'
  get 'comprobar' => 'escenarios#show'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]  
  resources :escenarios
  resources :escenario_ideals
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end
  
  def contact
    flash[:success] = "Tu correo ha sido enviado con éxito."
  end

  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "Sobre nosotros") %>

    <!-- Page Content -->
    <div class="container">

        <!-- Introduction Row -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Sobre nosotros
                    <small>¡Encantados de conocerte!</small>
                </h1>
                <p>Somos un cinco jóvenes estudiantes de la Universidad Complutense de Madrid que trabajamos para facilitarte el apredizaje en cuestiones de seguridad informática. <strong>¿Quieres aprender a protegerte en la red?</strong> Nosotros te enseñamos las reglas básicas del juego. Después, todo depende de ti.</p>
            </div>
        </div>

        <!-- Team Members Row -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Equipo Cloud Ender</h2>
            </div>
            <div class="row">
            <div class="col-md-4 text-center">
                <%= image_tag "fotoTodor.jpg", size: "140x140", class: "img-circle" %>
      <div class="caption">
        <h3>Todor Nikolaev</h3>
        <p><small>Portal Web, BBDD y Escenarios</small></p>
                <p class= "text-center">
        <a class="btn btn-linkedin" href="https://www.linkedin.com/pub/todor-velikov-usenliev/9b/97/656"><i class="fa fa-linkedin"></i></a>
       <a class="btn btn-github" href = "mailto: todornv@gmail.com"><i class="fa fa-envelope-o"></i></a></p>
            </div>
            </div>
            <div class="col-md-4 text-center">
                <%= image_tag "fotoJavi2.jpg", size: "140x140", class: "img-circle"%>
      <div class="caption">
        <h3>Javier Serrano</h3>
        <p><small>Arquitectura, Red y Escenarios</small></p>
        <p class= "text-center">
       <a class="btn btn-github" href = "mailto: jserrano1990@gmail.com"><i class="fa fa-envelope-o"></i></a></p>
            </div>
            </div>
            <div class="col-md-4 text-center">
                 <%= image_tag "fotoIratxe.jpg", size: "140x140", class: "img-circle"%>
      <div class="caption">
                <h3>Iratxe González Garrido</h3>
                    <p><small>Portal Web, BBDD y Escenarios</small></p>
                <p class="text-center">
        <a class="btn btn-linkedin" href="https://es.linkedin.com/in/iratxeggarrido"><i class="fa fa-linkedin"></i></a>
       <a class="btn btn-github" href="mailto: iratxe.ggarrido@gmail.com"><i class="fa fa-envelope-o"></i></a></p>
            </div>
            </div>
            <div class="col-md-4 text-center">
                 <%= image_tag "fotoSergio.jpg", size: "140x140", class: "img-circle"%>
      <div class="caption">
                <h3>Sergio Carvajal
                </h3>
                <p><small>Arquitectura, Red y Escenarios</small></p>
                <p class="text-center">
         <a class="btn btn-github" href="mailto: sergioca2081@gmail.com"><i class="fa fa-envelope-o"></i></a></p>
            </div>
            </div>
            <div class="col-md-4 text-center">
                 <%= image_tag "fotoDani.png", size: "140x140", class: "img-circle"%>
      <div class="caption">
                <h3>Daniel García</h3>
                <p><small>Portal Web, BBDD y Escenarios</small></p>
                <p class="text-center">
        <a class="btn btn-linkedin" href="https://www.linkedin.com/pub/daniel-garcia-gomez/69/b08/582"><i class="fa fa-linkedin"></i></a>
       <a class="btn btn-github" href="mailto: d.gargomez@gmail.com"><i class="fa fa-envelope-o"></i></a></p>
            </div>
            </div>
        </div>
</div>
        <hr>


    </div>
    <!-- /.container --> 

app/views/static_pages/contact.html.erb
<% provide(:title, "Contacto") %>
<h1>Contacto</h1>
<%= form_for @message, :url => contact_path, :html => {:class => "form-horizontal"} do |form| %>
<fieldset>
 <div class="control-group">
  <%= form.label :name, :class => "control-label" %>
  <div class="controls">
    <%= form.text_field :name %>
  </div>
 </div>

 <div class="control-group">
  <%= form.label :email, :class => "control-label" %>
  <div class="controls">
    <%= form.text_field :email %>
  </div>
 </div>

 <div class="control-group">
  <%= form.label :subject, :class => "control-label" %>
  <div class="controls">
    <%= form.text_field :subject %>
  </div>
 </div>

 <div class="control-group">
  <%= form.label :venue, :class => "control-label" %>
  <div class="controls">
    <%= form.text_field :venue %>
  </div>
 </div>

 <div class="control-group">
  <%= form.label :date, :class => "control-label" %>
  <div class="controls">
    <%= form.text_field :date %>
  </div>
 </div>

app/views/static_pages/help.html.erb
<% provide(:title, "Ayuda") %>
<h1>Ayuda</h1>
<p>

El objetivo de 'Cloud Ender' es que usuarios puedan desplegar escenarios virtuales de guerra digital, de modo que se puedan poner a prueba sus habilidades en ciber-seguridad. Estos escenarios, desplegados en la Nube, tendrán objetivos diferentes y se requerirá de diferentes herramientas y conocimientos para superarlos.

 
 <h2> Si necesitas ayuda, sigue los siguientes pasos para adentrarte en 'Cloud Ender' y enfrentarte a sus Escenarios de Ciberguerra </h2>

</p>

<ul class="list-group">
  <li class="list-group-item list-group-item-success">Paso 1: Regístrate en 'Cloud Ender' desde la página principal o desde el enlace 'Iniciar Sesión'</li>
  <li class="list-group-item list-group-item-info">Paso 2: Inicia sesión con tu usuario y contraseña desde el enlace 'Iniciar Sesión'</li>
  <li class="list-group-item list-group-item-warning">Paso 3: A continuación, debes pulsar sobre el enlace de 'Escenarios', elegir uno y pinchar sobre el botón 'Mostrar'</li>
  <li class="list-group-item list-group-item-danger">Paso 4: Para lanzar el Escenario, pulsa sobre el botón 'Lanzar'. Después de unos minutos, se visualizará un mensaje informativo sobre el correcto lanzamiendo del escenario</li>
  <li class="list-group-item list-group-item-success">Paso 5: Una vez que el Escenario se haya lanzado, se habilitará un enlace para la descarga de los certificados digitales, necesarios para conectarte por VPN a la red del Escenario virtual desplegado</li>
  <li class="list-group-item list-group-item-info">Paso 7: Instala los certificados que acabas de descargar y usa 'OpenVPN' para conectarte al Escenario</li>
  <li class="list-group-item list-group-item-warning">Paso 8: Por último, si has sido capaz de superar el reto del Escenario, utiliza el botón de 'Comprobar resultado' para verificar que los resultados obtenidos son realmente los que se pedían.</li>
</ul>

app/views/static_pages/home.html.erb
<% if logged_in? %>
<% provide(:title, 'Usuario') %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>


<% provide(:title, "Home") %>
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="5000">
 <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
      <div class="carousel-inner">
        <div class="item">
          <%= image_tag "seguridad1.jpg", class: "media-object"%>
          <div class="container">
            <div class="carousel-caption">
            </div>
          </div>
        </div>
        <div class="item ">
          <%= image_tag "seguridad2.jpg", class: "media-object"%>
          <div class="container">
            <div class="carousel-caption">
              <h1>Cloud Computing</h1>
              <p class="lead">La nube es la nueva forma optimizada de prestación de servicios para el tratamiento de la información.</p>
              
            </div>
          </div>
        </div>
        <div class="item active">
          <%= image_tag "seguridad3.jpg", class: "media-object"%>
          <div class="container">
            <div class="carousel-caption">
              <h1>Ciberseguridad</h1>

              <p class="lead">La seguridad IT es una de las grandes preocupaciones de la sociedad del siglo XXI, tanto a nivel corporativo como a nivel particular.</p>
              <%= link_to "Regístrate en Ender", signup_path, class: "btn btn-large btn-primary" %>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="http://getbootstrap.com/examples/carousel/#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Anterior</span>
      </a>
      <a class="right carousel-control" href="http://getbootstrap.com/examples/carousel/#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Siguiente</span>
      </a>
    </div><!-- /.carousel -->
</br>
</br>

<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

      <h1>Tecnologías utilizadas</h1>
       <hr class="featurette-divider">
  <!-- Three columns of text below the carousel -->
  <div class="row">
    <div class="col-md-4 text-center">
    <%= image_tag "ruby.png", size: "140x140"%>
      <h2>Ruby</h2>
    </div>
    <div class="col-md-4 text-center">
      <%= image_tag "opennebula.png", size: "205x140"%>
      <h2>Open Nebula</h2>
    </div>
    <div class="col-md-4 text-center">
      <%= image_tag "github.png", size: "140x140"%>
      <h2>GitHub</h2>
    </div>


  </div><!-- /.row -->
  </br>
 <div class="row">

    <div class="col-md-4 text-center">
      <%= image_tag "bootstrap.png", size: "140x140"%>
      <h2>Bootstrap</h2>
    </div>
     <div class="col-md-4 text-center">
      <%= image_tag "rails.png", size: "110x140"%>
      <h2>Rails</h2>
    </div>
    <div class="col-md-4 text-center">
      <%= image_tag "openvpn.png", size: "140x140"%>
      <h2>OpenVPN</h2>
    </div>
</div>
   
<% end %>