config/routes.rb
Rails.application.routes.draw do

#Definir named routes
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'loading' => 'escenarios#new'
  get 'contact', to: 'messages#new', as: 'contacto'
  post 'contact', to: 'messages#create'
  get 'comprobar' => 'escenarios#show'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]  
  resources :escenarios
  resources :escenario_ideals
end

app/models/escenario_ideal.rb
class EscenarioIdeal < ActiveRecord::Base
  #attr_accessible :descripcion, :dificultad, :nombre, :script_maquinas
  has_many :escenarios
  mount_uploader :picture, PictureUploader
end

app/controllers/escenario_ideals_controller.rb
class EscenarioIdealsController < ApplicationController
  before_action :set_escenario_ideal, only: [:show, :edit, :update, :destroy]

  # GET /escenario_ideals
  # GET /escenario_ideals.json
  def index
    @escenario_ideals = EscenarioIdeal.all
  end

  # GET /escenario_ideals/1
  # GET /escenario_ideals/1.json
  def show
    @escenario_ideal = EscenarioIdeal.find(params[:id])

  end

  # GET /escenario_ideals/new
  def new
    @escenario_ideal = EscenarioIdeal.new
  end

  # GET /escenario_ideals/1/edit
  def edit
  end

  # POST /escenario_ideals
  # POST /escenario_ideals.json
  def create
    @escenario_ideal = EscenarioIdeal.new(escenario_ideal_params)

    respond_to do |format|
      if @escenario_ideal.save
        flash[:success] = "El escenario se ha creado con éxito."
        format.html { redirect_to @escenario_ideal, notice: 'Escenario ideal was successfully created.' }
        format.json { render :show, status: :created, location: @escenario_ideal }
      else
        flash[:danger] = "El escenario no se ha podido crear."
        format.html { render :new }
        format.json { render json: @escenario_ideal.errors, status: :unprocessable_entity }
      end
    end
  end
 
  # PATCH/PUT /escenario_ideals/1
  # PATCH/PUT /escenario_ideals/1.json
  def update
    if @escenario_ideal.update_attributes(escenario_ideal_params)
      flash[:success] = "Escenario actualizado con éxito"
      redirect_to @escenario_ideal
    else
      render 'edit'
    end
  end

  # DELETE /escenario_ideals/1
  # DELETE /escenario_ideals/1.json
  def destroy

    EscenarioIdeal.find(params[:id]).destroy
    flash[:success] = "Escenario eliminado con éxito"
    redirect_to escenario_ideals_url
   
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_escenario_ideal
      @escenario_ideal = EscenarioIdeal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def escenario_ideal_params
      params.require(:escenario_ideal).permit(:nombre, :descripcion, :dificultad, :script_maquinas, :mv_array, :picture)
    end
end

app/helpers/escenario_ideals_helper.rb
module EscenarioIdealsHelper
end

app/views/escenario_ideals/_form.html.erb
<% provide(:title, 'Editar escenario') %>
<%= form_for(@escenario_ideal, html: { multipart: true }) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
  <div class="row">
  <div class="col-md-6 col-md-offset-3">
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :dificultad %><br>
    <%= f.number_field :dificultad, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :script_maquinas %><br>
    <%= f.text_area :script_maquinas, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :mv_array %><br>
    <%= f.text_field :mv_array, class: 'form-control' %>
  </div>
  <span class="picture">
  <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </span>
  <div class="actions">
    <%= f.submit "Guardar cambios", class: "btn btn-primary" %>
  </div>
  </div>
  </div>
<% end %>

app/views/escenario_ideals/edit.html.erb
<h1>Editing Escenario Ideal</h1>

<%= render 'form' %>

<%= link_to 'Show', @escenario_ideal %> |
<%= link_to 'Back', escenario_ideals_path %>

app/views/escenario_ideals/index.html.erb
<% provide(:title, 'Escenarios') %>
<h1>Escenarios</h1>
<% @escenario_ideals.each do |escenario_ideal| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title"><%=escenario_ideal.nombre %></h2>
  </div>
  <div class="panel-body">
<div class="row">
<div class="col-md-3">
<%= image_tag escenario_ideal.picture.url, class: "img-thumbnail" if escenario_ideal.picture? %></div>
  <div class="col-md-9">
    <div class="list-group">

  <div class="list-group-item">
    <!--<h4 class="list-group-item-heading">Descripción</h4>-->
    <p class="text-justify"><%= escenario_ideal.descripcion %></p>
  </div>
  <div class="list-group-item">
    Dificultad <span class="badge"><%= escenario_ideal.dificultad %></span> 
</div>
  </div>
</div>
</div>
  </div>
<div class="panel-footer">
  <div class="btn-toolbar" role="toolbar" aria-label="...">
 
  
  <%= link_to "Mostrar", escenario_ideal_path(escenario_ideal), class: "btn btn-default", :type => "button"%><% if current_user.admin? %>
<%= link_to 'Editar', edit_escenario_ideal_path(escenario_ideal), :class => "btn btn-default", :role => "button"%>
        <% end %>     
   </div>
</div>

</div>

<% end %>
<% if current_user.admin? %>
<div class="btn-group btn-group-justified" role="group" aria-label="...">
  <%= link_to 'Nuevo Escenario', new_escenario_ideal_path, :class => "btn btn-primary btn-lg btn-justified", :type => "button"%>
</div>
<% end %>

app/views/escenario_ideals/loading.html.erb
<% provide(:title, 'Cargando') %>
<script>
 
function autoRefresh()
{
window.location = window.location.href;
}
 
setInterval('autoRefresh()', 5000); // this will reload page after every 5 secounds; Method I
</script>

    <div class="jumbotron">
      <div class="container">
        <h1>Cargando</h1>
        <p>Estamos cargando el escenario, por favor espera unos instantes.</p>
        <div class="progress">
		<% if des=File.exist?("/var/lib/one/escenarios/ES001/dir") %>
                	<div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%"></div>
		<% elsif des=File.exist?("/var/lib/one/escenarios/ES001/desp") %>
			<div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%"></div>
		<% elsif des=File.exist?("/var/lib/one/escenarios/ES001/cert") %>
			<div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%"></div>
		<% end %>
        </div>
     </div>
<h1>id_escenario_ideal=<%= @escenario_ideal.id %></h1>
<h1>current_user id=<%= @current_user.id %></h1>
   </div>

app/views/escenario_ideals/new.html.erb
<h1>New Escenario Ideal</h1>

<%= render 'form' %>

<%= link_to 'Back', escenario_ideals_path %>

app/views/escenario_ideals/show.html.erb
<% provide(:title, @escenario_ideal.nombre) %>
<% @escenario = Escenario.find_by id_escenario_ideal:@escenario_ideal.id, id_user: current_user.id %>
<div class="panel panel-default">
  <div class="panel-heading">
   <strong><h2 class="panel-title"><%= @escenario_ideal.nombre %></h2></strong>
  </div>
  <div class="panel-body">
<div class="row">
<div class="col-md-3">
<%= image_tag @escenario_ideal.picture.url, class: "img-thumbnail" if @escenario_ideal.picture? %>
 </div>
  <div class="col-md-9">
    <div class="list-group">

  <div class="list-group-item">
    <!--<h4 class="list-group-item-heading">Descripción</h4>-->
    <p class="text-justify"><%= @escenario_ideal.descripcion %></p>
  </div>
  <div class="list-group-item">
    Dificultad <span class="badge"><%= @escenario_ideal.dificultad %></span> 
</div>
<% if current_user.admin? %>
<div class="list-group-item">
    <strong><h4 class="list-group-item-heading">Recursos</h4></strong>
    <p class="text-justify"><%= @escenario_ideal.script_maquinas %></p>
  </div>
<div class="list-group-item">
    <strong><h4 class="list-group-item-heading">Mv array</h4></strong>
    <p class="text-justify"><%= @escenario_ideal.mv_array %></p>
  </div>
<% end %>
  </div>
 </div>
 </div>
  </div>
  <div class="panel-footer">
  <div class="btn-toolbar" role="toolbar" aria-label="...">
  <% if !Escenario.exists?(id_escenario_ideal: @escenario_ideal.id, id_user: current_user.id) %>
    <%= link_to "Lanzar",  new_escenario_path(id_escenario_ideal: @escenario_ideal.id, current_user: current_user.id, script: @escenario_ideal.script_maquinas, mv: @escenario_ideal.mv_array), class: "btn btn-success", :type => "button" %>
  <% end %>
 <% if Escenario.exists?(id_escenario_ideal: @escenario_ideal.id, id_user: current_user.id)%>
  <%= link_to 'Parar', escenario_path(@escenario), method: :delete,   data: {
          confirm: '¿Estás seguro/a?',
          :confirmButtonText => 'Sí',
          cancelButtonText: "Mejor no",
          type: "danger",
          text: 'Esto eliminará todo el progreso que hayas hecho hasta ahora.'
        }  ,  :class => "btn btn-danger", :role => "button"%> 
 <%= link_to "Comprobar resultado", escenario_path(@escenario), class: "btn btn-default", :type => "button"%> 
 <% end %>
   </div>
</div>
</div>
  <nav>
  <ul class="pager">
<% if current_user.admin? %>

 <%= link_to 'Editar', edit_escenario_ideal_path(@escenario_ideal) %> 
 <% end %>

    <li class="previous"><%= link_to '    Atrás', escenario_ideals_path, class: "fa fa-arrow-left" %></li>
  </ul>
</nav>