config/routes.rb
Rails.application.routes.draw do

#Definir named routes
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'loading' => 'escenarios#new'
  get 'contact', to: 'messages#new', as: 'contacto'
  post 'contact', to: 'messages#create'
  get 'comprobar' => 'escenarios#show'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]  
  resources :escenarios
  resources :escenario_ideals
end

app/models/escenario.rb
class Escenario < ActiveRecord::Base
  #attr_accessible :id_escenario_ideal
  has_one :escenario_ideal
  #has_many :maquina
  belongs_to :user
  mount_uploader :fichero, FicheroUploader
end

app/controllers/escenarios_controller.rb
class EscenariosController < ApplicationController
  before_action :set_escenario, only: [:show, :edit, :update, :destroy]
  #attr_accessible :id_escenario_ideal
  #has_one :escenario_ideal
  #has_many :maquina
  #belongs_to :user
  # GET /escenarios
  # GET /escenarios.json
  def index
    @escenarios = Escenario.all
  end

  # GET /escenarios/1
  # GET /escenarios/1.json
  def show
    #@ruta="su oneadmin -c \"/var/lib/one/validacion.sh "+@escenario.id.to_s+" &\""
    #if system(@ruta) == true
     # flash[:success] = "¡Escenario superado! #{view_context.link_to("Volver al escenario.", @escenario)}" 
    #else
      #flash[:danger] = "Lo sentimos, pero tu fichero no es correcto."
    #end
  end

  # Comprueba que el fichero que sube el usuario es igual que el del escenario ideal
  def comprobar
    
  end

  # GET /escenarios/new
   def new
    @escenario_ideal_id = params[:id_escenario_ideal] 
    @user_id = params[:current_user]
    @escenario_ideal_script = params[:script]
    @escenario_ideal_mv = params[:mv]
    if !Escenario.exists?(id_escenario_ideal: @escenario_ideal_id, id_user: @user_id)
      @escenario = Escenario.create(:id_escenario_ideal => @escenario_ideal_id, :id_user => @user_id)
   # if !des=File.exist?("/var/lib/one/escenarios/"+@escenario.id.to_s+"")
      @ruta="su oneadmin -c \"/var/lib/one/crea.sh "+@escenario.id.to_s+" "+@escenario_ideal_script+" "+@escenario_ideal_mv+" &\""
      system(@ruta)
    else
      @escenario=Escenario.find_by(id_escenario_ideal: @escenario_ideal_id, id_user: @user_id )
    end
    
     #system(@ruta)
   
    if @escenario.estado.to_s == "exito"
    flash[:success] = "Es escenario se ha desplegado con éxito. ¡Descárgate los 
    #{view_context.link_to("certificados", "/certificados/"+@escenario.id.to_s+".zip")}, y empieza a practicar!"
    flash[:info] = "#{view_context.link_to("Volver al escenario.", @escenario)}" 
    end
  end
  # GET /escenarios/1/edit
  def edit
  end

  # POST /escenarios
  # POST /escenarios.json
  def create
    @escenario = Escenario.new(escenario_params)

    respond_to do |format|
      if @escenario.save
        format.html { redirect_to @escenario, notice: 'Escenario was successfully created.' }
        format.json { render :show, status: :created, location: @escenario }
      else
        format.html { render :new }
        format.json { render json: @escenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /escenarios/1
  # PATCH/PUT /escenarios/1.json
  def update
    #respond_to do |format|
    if @escenario.update(escenario_params)
        @ruta="su oneadmin -c \"/var/lib/one/validacion.sh "+@escenario.id.to_s+" \""
	      system(@ruta) 
	      @escenario=Escenario.find_by(id: @escenario.id )
	      if @escenario.estado.to_s == "sup"
        	flash[:success] = "¡Escenario superado! " #{view_context.link_to("Volver al escenario.", @escenario)}" 
    		  @ruta="su oneadmin -c \"/var/lib/one/cierre.sh "+@escenario.id.to_s+" &\""
      		system(@ruta)
      		redirect_to escenario_ideals_url
	      else
        	flash[:danger] = "Lo sentimos, pero tu fichero no es correcto."
		      redirect_to @escenario
        end 
        #format.html { redirect_to @escenario, notice: 'Escenario was successfully updated.' }
        #format.json { render :show, status: :ok, location: @escenario }
      #else
       # format.html { render :edit }
        #format.json { render json: @escenario.errors, status: :unprocessable_entity }
    end
  end

  # DELETE /escenarios/1
  # DELETE /escenarios/1.json
  def destroy
    @escenario.destroy
     @ruta="su oneadmin -c \"/var/lib/one/cierre.sh "+@escenario.id.to_s+" &\""
      system(@ruta)
    #respond_to do |format|
     # format.html { redirect_to escenarios_url, notice: 'Escenario was successfully destroyed.' }
      #format.json { head :no_content }
    #end
    flash[:success] = "Escenario parado con éxito"
    redirect_to escenario_ideals_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_escenario
      @escenario = Escenario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def escenario_params
      params.require(:escenario).permit(:id_escenario_ideal, :id_user, :fichero)

    end
end

app/helpers/escenarios_helper.rb
module EscenariosHelper
end

app/views/escenarios/_form.html.erb
<%= form_for(@escenario) do |f| %>
  <% if @escenario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@escenario.errors.count, "error") %> prohibited this escenario from being saved:</h2>

      <ul>
      <% @escenario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_escenario_ideal %><br>
    <%= f.number_field :id_escenario_ideal %>
  </div>
  <div class="field">
    <%= f.label :id_user %><br>
    <%= f.number_field :id_user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/escenarios/comprobar.html.erb
<% provide(:title, 'Comprobar resultado') %>
<h1>Comprobar resultado</h1>
<%= form_for(@escenario, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
<span class="picture">
<%= f.file_field_tag 'picture' %>
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
  <%= f.submit "Publicar", class: "btn btn-primary" %>
  
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('El tamaño máximo del fichero son 5MB. Por favor elige un fichero más pequeño.');
    }
  });
</script>

app/views/escenarios/edit.html.erb
<h1>Editing Escenario</h1>

<%= render 'form' %>

<%= link_to 'Show', @escenario %> |
<%= link_to 'Back', escenarios_path %>

app/views/escenarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Escenarios</h1>

<table>
  <thead>
    <tr>
      <th>Id escenario ideal</th>
      <th>Id user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @escenarios.each do |escenario| %>
      <tr>
        <td><%= escenario.id_escenario_ideal %></td>
        <td><%= escenario.id_user %></td>
        <td><%= link_to 'Show', escenario %></td>
        <td><%= link_to 'Edit', edit_escenario_path(escenario) %></td>
        <td><%= link_to 'Destroy', escenario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Escenario', new_escenario_path %>

app/views/escenarios/new.html.erb
<% provide(:title, 'Cargando') %>
<script>

function autoRefresh()
{
window.location = window.location.href;
}

setInterval('autoRefresh()', 5000); // this will reload page after every 5 secounds; Method I
</script>
<% @des=@escenario.estado.to_s %>
<% @texto = "Este proceso puede tardar unos minutos"%>
 <% if @des=="dir" %>
        <% @texto="Buscando nodo" %> <% @pos="10" %>
 <% elsif @des=="nodo" %>
        <% @texto="Desplegando maquinas" %> <% @pos="20" %>
 <% elsif @des=="desp" %>
        <% @texto="Configurando VPN" %> <% @pos="80" %>
 <% elsif @des=="confg" %>
        <% @texto="Generando archivos de conexion VPN" %> <% @pos="90" %>
 <% elsif @des=="exito" %>
        <% @texto="Escenario desplegado con exito" %> <% @pos="100" %>
 <% end %>
    <div class="jumbotron">
      <div class="container">
        <h1>Cargando</h1>
        <p>Estamos cargando el escenario: <%= @texto %>.</p>
        <div class="progress">
           <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="<%= @pos %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @pos %>%"></div>
        </div>
        <% if @des=="fail" %>
                        <h1>Error al desplegar el escenario</h1>
        <% end %>
     </div>
   </div>
~                      

app/views/escenarios/show.html.erb
<% provide(:title, 'Comprobar resultado') %>
<h1>Comprobar resultado</h1>
<%= form_for(@escenario, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
<span class="field">
    <%= f.file_field :fichero, accept: 'text/html' %>
  </span>
  <%= f.submit "Comprobar resultado", class: "btn btn-primary" %>
  
<% end %>