config/routes.rb
Rails.application.routes.draw do

#Definir named routes
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'loading' => 'escenarios#new'
  get 'contact', to: 'messages#new', as: 'contacto'
  post 'contact', to: 'messages#create'
  get 'comprobar' => 'escenarios#show'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]  
  resources :escenarios
  resources :escenario_ideals
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Trabajo Fin de Grado <a href='http://ender.dacya.ucm.es/'>ENDER</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Sobre nosotros", about_path %></li>
      <li><%= link_to "Contacto", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand" href="#">
        <%= image_tag "logo.png", size: "30x30"%>
      </a>
    <%= link_to "ender", root_path, id: "logo" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
       <ul class="nav navbar-nav navbar-right">
       <% if logged_in? %>
        <li><%= link_to "Perfil", root_path %></li>
         <% else %>
         <li><%= link_to "Home",   root_path %></li>
        <% end %>
        <li><%= link_to "Ayuda",   help_path %></li>
        <% if logged_in? %>
        <li><%= link_to "Escenarios",   escenario_ideals_path %></li>
          <li><%= link_to "Usuarios", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Cuenta <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Perfil", current_user %></li>
              <li><%= link_to "Ajustes", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Cerrar sesión", logout_path,  method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Iniciar sesión", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<%= favicon_link_tag 'favicon.ico' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= favicon_link_tag %>
    <title><%= yield(:title) %> | Ender</title>
    <%= stylesheet_link_tag    'application', media: 'all', 
                                              'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
<% if message.is_a?(String) %>
 <div class="alert alert-<%= message_type %>"> <%= sanitize(message) %>
   <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> </div>
    <% else %>
        <div class="alert alert-<%= message_type %>"><%= message %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> </div>
<% end %>
      
        

      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

      